### ISSUE TITLE
Enable console output

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-java#101]
**Is your feature request related to a problem? Please describe.**

To help to debug it would be nice to enable console output. However, that doesn't seem possible with the agent today.

**Describe the solution you'd like**

A config flag that enables console output.

**Describe alternatives you've considered**

Stand up a local otel collector configured with the console output and point the agent at that. This works but is a lot of effort.

**Additional context**

**Comment by JamieDanielson** [comment]
Removing stale

**Comment by MikeGoldsmith** [comment]
Need to understand whether this is for one or both of:
- agent with enrichment
- manual

**Comment by bdarfler** [comment]
https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/2270 exists for the agent and https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java exists for manual instrumentation.

Closing this and leaving documentation up to https://github.com/honeycombio/honeycomb-opentelemetry-java/issues/91
