### ISSUE TITLE
Add WithSpan example to docs

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-java#105]
When using the Java auto-instrumentation agent, a convenient way to get a custom span is to decorate a method with `@WithSpan`. Maybe add an example of that to the [Creating New Spans](https://docs.honeycomb.io/getting-data-in/java/opentelemetry-distro/#creating-new-spans) section to contrast with the example already there for getting the tracer and creating a span from within a method.

**Comment by JamieDanielson** [comment]
Removing stale
