### ISSUE TITLE
Set telemetry.sdk.* in Java Beestro *SDK* (not agent)

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#116]
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#telemetry-sdk

Set the `telemetry.sdk.*` attributes in the SDK produced by our configurer

- if we make it something specific to us (e.g. opentelemetry-honeycomb), we don't need to do anything else for #131 
- but is that accurate? do we actually produce our own "SDK"?

**Comment by MikeGoldsmith** [comment]
Now that we've updated our package to not be a wrapper of the OTel SDK in #132 and return a configured OTel SDK instance, I think we should leave the defaults for the `telemetry.sdk.*` attributes which will be set by the OTel Java SDK.

**Comment by MikeGoldsmith** [comment]
Moving back to "In Progress" to verify the SDK attributes are set correctly.
