### ISSUE TITLE
Differentiate between plain SDK and agent in the metadata

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#131]
We cannot currently differentiate SDK-only users from agent users. Add/augment resource attributes to let us differentiate those. (We can use `telemtry.sdk.*` - though we don't _technically_ provide our own SDK. Alternatively, we can use our own `honeycomb.distro.*` attributes)

**Comment by MikeGoldsmith** [comment]
Closing as per note in #147 - the agent sets `sdk.auto.version` which can be used to differentiate between SDK and agent telemetry data.
