### ISSUE TITLE
Allow vars to be specified via a prop file?

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#14]
Looks like OTEL has an undocumented support for this: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/javaagent-tooling/src/main/java/io/opentelemetry/javaagent/tooling/config/ConfigInitializer.java#L26

Precedence goes system properties >> env vars >> prop file

**Comment by JamieDanielson** [comment]
Removing stale, should only be on new issues as of Sept 1.

**Comment by MikeGoldsmith** [comment]
Docs ticket: https://github.com/honeycombio/docs/pull/1045
