### ISSUE TITLE
React to java agent name change from upstream OTel

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-java#150]
This is just a reminder issue to monitor java agent name change from upstream OTel - we'll likely need to update our dependency to remove "-all" in an upcoming release, once this change goes live and we update our dependencies.

https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/3959#issuecomment-925486206

**Comment by bdarfler** [comment]
Looks like this got merged - https://github.com/open-telemetry/opentelemetry-java-instrumentation/pull/4106
