### ISSUE TITLE
Add happy path integration test for metrics

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#168]
[One-pager](https://honeycomb.quip.com/kTyJA9ueDiAa/Beestro-Testing-One-Pager)

Closely related to #133 -- might be blocked on that, until we know the shape of the test.

Add metrics verification to the happy path test suite. (Agent examples only? Users can create their own metrics using the SDK, but that's essentially just the vanilla OTEL functionality, which we're not trying to validate here)

**Comment by MikeGoldsmith** [comment]
Closed as part of #206
