### ISSUE TITLE
addResourceAttribute Breaks Builder's Fluent Interfaces

### ISSUE THREAD

**Issue by omervk** [honeycombio/honeycomb-opentelemetry-java#191]
`OpenTelemetryConfiguration.Builder` uses the Builder pattern to build an instance of `OpenTelemetry`. To do that, every method on the class returns `this` so that the fluent interface may continue.
Unfortunately, calls to `addResourceAttribute` do not return `this`, instead returning the internal `AttributesBuilder`, preventing continued calls to the original builder.

Expected:
```
OpenTelemetryConfiguration.builder()
        // ...
        .addResourceAttribute("service.version", version)
        .buildAndRegisterGlobal();
```

Actual:
```
OpenTelemetryConfiguration.builder()
        // ...
        .addResourceAttribute("service.version", version)
        .buildAndRegisterGlobal(); // <- Compile-error
```

Workaround:
```
OpenTelemetryConfiguration.Builder builder = OpenTelemetryConfiguration.builder()
        // ...
builder.addResourceAttribute("service.version", version)
builder.buildAndRegisterGlobal();
```

**Comment by MikeGoldsmith** [comment]
Thanks for raising this bug @omervk - we'll take a look and update this issue as required.
