### ISSUE TITLE
Use the OTel Sampling Algorithim

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-java#196]
**Is your feature request related to a problem? Please describe.**

The current sampler implementation uses the beeline algorithm for sampling. Unfortunately, this is not compatible with the algorithm that OTel uses which means that this distro cannot play nicely with other OTel SDKs.

**Describe the solution you'd like**

- [x] Update the sampler implementation to delegate to the stock OTel TraceIdRatio sampler.
- [x] Ensure that the proper `sample_rate` attribute is still set so that Honeycomb can show proper graphs.
- [x] Research using TraceIdRatio vs ParentBased(root=TraceIdRatio) and decide which to use.
- [ ] Research the sampling [config autoconfigure settings](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#sampler) and decide if and how we work with them.

**Comment by MikeGoldsmith** [comment]
#209 updates the distro to use the core OTel Parent & TraceIdRatio samplers with the configuration setup so that if the parent context has been sampled, it will use the same decision and when the parent context does not have a sampling decision the Trace ID ratio sampler is used.
