### ISSUE TITLE
docs: add the "advanced" use case of using vanilla OTel

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-java#198]
Make it clear in the README/public docs that a more advanced configuration is possible by using vanilla OTEL. Add minimal instructions for necessary headers and endpoints.

Note: this is a first pass, as we don't have many people asking how to use vanilla OTEL, where distros exist. We may go down the path of adding full docs for setting up vanilla OTEL and distros, but we will need to consider how to do that in such a way that the majority of users don't get confused by those options ("wait, which one should I use?")

**Comment by bdarfler** [comment]
This could be a good place to add sampler docs and baggagespanprocessor docs when we get to those items. No need to pick them up in this issue.

**Comment by JamieDanielson** [comment]
Closed with honeycombio/docs#1049
