### ISSUE TITLE
Test for SDK baggage attributes

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#204]
[One-Pager](https://honeycomb.quip.com/kTyJA9ueDiAa/Beestro-Testing-One-Pager)

Add a test that validates that an example app that just uses the SDK and configures a baggage span processor appends baggage attributes that come in with request payload.

**Comment by robbkidd** [comment]
I propose that this is addressed in #205 in [the SDK unit test for BaggageSpanProcessor.](https://github.com/honeycombio/honeycomb-opentelemetry-java/pull/205/files#diff-f73de19d92dee2786a6d6e7004a390ee56da970c733015792677df498c165784R34)
