### ISSUE TITLE
Global attributes to every span

### ISSUE THREAD

**Issue by sergi-mm** [honeycombio/honeycomb-opentelemetry-java#243]
Hello,

I'm usign the HoneyComb OpenTelemetry Java agent in a Spring Boot project and after some investigation I cannot find how to add **global key-value** attributes on each request. 

For instance, we want to know on which cluster happened every action, so we have an environment variable called CLUSTER_NAME. 

I want to add this environment variable to every trace sent to Honeycomb, but I only found the option to manually add this data on each method by manually getting the current Span and adding the fields to the span. But this should be done on **every request and method** and it's very inconvenient.

I also tried adding [multi-span attributes](https://docs.honeycomb.io/getting-data-in/java/opentelemetry-distro/#multi-span-attributes) but does not work.

Anybody can help me?

**Comment by MikeGoldsmith** [comment]
Hey @sergi-mm - I think what you're looking for is to set [OTel resource attributes](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#opentelemetry-resource) which can se set either via system properties or environment variables.

Resource attributes describe details about your system that does not change, eg host or environment details 👍🏻
