### ISSUE TITLE
Publish snapshots to snapshot repo in Maven

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-java#258]
**Is your feature request related to a problem? Please describe.**

It doesn't seem like the snapshots are actually being published anywhere in Maven that can be accessed. I think we need to specify a snapshot repository for uploading.

**Additional context**

[Circle publish_maven job](https://app.circleci.com/pipelines/github/honeycombio/honeycomb-opentelemetry-java/1032/workflows/65a8533c-284c-48ea-b371-229985b73dd5/jobs/4134) shows success but the snapshot cannot be found in Maven.

**Comment by vreynolds** [comment]
They're [there](https://oss.sonatype.org/content/repositories/snapshots/io/honeycomb/honeycomb-opentelemetry-javaagent/0.9.1-SNAPSHOT/), you probably just need to add the snapshots repo to `build.gradle` wherever you're trying to use them:

```
repositories {
    mavenCentral()
    mavenLocal()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
        mavenContent {
            snapshotsOnly()
        }
    }
}
```

**Comment by JamieDanielson** [comment]
Ah perfection! Knew something was missing somewhere 😄
