### ISSUE TITLE
464 errors from api.honeycomb.io?

### ISSUE THREAD

**Issue by robbkidd** [honeycombio/honeycomb-opentelemetry-java#279]
Some folks are reporting receiving 464 error responses to sending data with the v1.0.0 release of this OTel distribution. 

```
ERROR [stderr] (OkHttp https://api.honeycomb.io/...) [otel.javaagent <timestamp>]
  [OkHttp https://api.honeycomb.io/...]
  WARN io.opentelemetry.exporter.internal.grpc.OkHttpGrpcExporter
  - Failed to export spans. Server responded with HTTP status code 464. Error message:
```

```
WARN 1 --- [oneycomb.io/...] i.o.e.internal.grpc.OkHttpGrpcExporter
   : Failed to export spans. Server responded with HTTP status code 464. Error message:
```

Gathering information about how/why in this issue.

### Case 1

**Versions**

😭 
- Java: Oracle JDK 1.8.0_151 (RHEL 6.10, x86_64)
- Honeycomb OpenTelemetry Distribution: 1.0.0

✅ 
- Java: OpenJDK 1.8.0_322 (macOS)
- Honeycomb OpenTelemetry Distribution: 1.0.0

### Case 2

**Versions**

😭 
- Java: [GraalVM 1.0.0-rc6](https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc6) 
- Honeycomb OpenTelemetry Distribution: 1.0.0

✅ 
- Java: [GraalVM 1.0.0-rc6](https://github.com/oracle/graal/releases/tag/vm-1.0.0-rc6) 
- Honeycomb OpenTelemetry Distribution: 0.6.1

**Steps to reproduce**

1. Have:
  - a clone of this repo
  - a recent JVM to build with in the dev environment
  - Docker and Docker Compose
2. `make build`
3. Change [the smoke test's x-app-base image](https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/0fa2f9e338a302ae040c2b40215775a7142e10a5/smoke-tests/docker-compose.yml#L4) to `image: findepi/graalvm:1.0.0-rc6`
4. Comment out [the smoke test's x-app-base HONEYCOMB_API_ENDPOINT environment variable](https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/0fa2f9e338a302ae040c2b40215775a7142e10a5/smoke-tests/docker-compose.yml#L6) to send data to Honeycomb and our real load balancer.
5. `make smoke-sdk`
6. See a 464 error in the logs for the smoke test's app-sdk container.

**Additional context**

**Comment by robbkidd** [comment]
So far, the commonality is New Distro, Old Java.

One thing that stands out to me in the 464 errors we see from our load balancers is the grpc library used by default by upstream OTel and carried down to us: okhttp. This was introduced in upstream OTel 1.9.0 which this distro started using in v0.8.0. Previously, our default was netty shadow-baked in.

**Comment by robbkidd** [comment]
Older JVMs (or JVM images) lack the key libraries necessary for HTTP/2 support required by gRPC. (Reference [a conversation in CNCF Slack](https://cloud-native.slack.com/archives/C0150QF88FL/p1642719024062100) about roughly this issue.) gRPC connections are downgraded to HTTP/1.1 which causes our ingest load balancer at AWS to return the 464 error (considering it a malformed request). This lack of native HTTP/2 support became apparent when OpenTelemetry Java removed the built-in dependency on grpc/netty.

I was able to send data to Honeycomb with the current latest version (v1.12.0) of upstream OpenTelemetry SDK and javaagent by configuring both for **OTLP/http+protobuf** export. http/protobuf is fine sent as HTTP/1.1.

Sample upstream agent config via environment variables:

```
OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io:443
OTEL_EXPORTER_OTLP_HEADERS: x-honeycomb-team=<a_key>,x-honeycomb-dataset=<target_dataset>
OTEL_SERVICE_NAME: <a_service_name>
```

The Honeycomb distribution of OpenTelemetry Java currently only implements an OTLP/gRPC exporter. We are considering adding an option to select between OTLP/gRPC and OTLP/http+protobuf.

**Comment by robbkidd** [comment]
The plan is to address this issue with #282 in the very near future.

@MikeGoldsmith I propose leaving this issue open until we get some words about 464 ingest errors with OpenTelemetry written up in the docs for troubleshooting. Probably under general OpenTelemetry troubleshooting and/or something specific about old JVMs with OTel Java.

**Comment by MikeGoldsmith** [comment]
@robbkidd added [docs PR](https://github.com/honeycombio/docs/pull/1244) that will close this issue when merged 👍🏻
