### ISSUE TITLE
Add option to add span processors to the SDK builder

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#33]
Currently there's no way to use the BaggageSpanProcessor (or add any span processor other than the defaulted `BatchSpanProcessor`) when using the Honey SDK.

**Comment by robbkidd** [comment]
What would an SDK user like to say? _Adding_ span processors can get pretty leaky, [exposing the OTel span processor builder which would require the developer to also build the exporter](https://github.com/honeycombio/honeycomb-opentelemetry-java/blob/v0.1.0/sdk/src/main/java/io/honeycomb/opentelemetry/HoneycombSdk.java#L178-L186).

One option: we expose a choice between enabling or disabling "multi-span attributes" ...

```java
HoneycombSdk honeycomb = new HoneycombSdk.Builder()
    .setSomeThings(...)
    .enableMultiSpanAttributes()
    .build();
```

If enabled, our SDK builder uses a BaggageSpanProcessor. If disabled (default), our SDK builder does what it does today: uses a BatchSpanProcessor.

**Comment by vreynolds** [comment]
It's hard to say for sure, since the SDK use case is still not very sharp (in my brain). I was envisioning the same pattern we use for the sampler today:
```
new HoneycombSdk.Builder()
  .addSpanProcessor(new BaggageSpanProcessor()) // or any other span processor they chose to define
  .build()
```

**Comment by robbkidd** [comment]
Yea. I'm currently challenged by the span processor's expectation of an exporter instance as a parameter in the constructor. So the user of our builder would need to construct an exporter first. 😕

**Comment by vreynolds** [comment]
The exporter is only needed for the BatchSpanProcessor, though, right? We configure that one behind the scenes. They can just construct the BaggageSpanProcessor with no args. Anything else custom will be their own home-baked AddCoolnessToSomeSpansOrSomething span processor.
