### ISSUE TITLE
Distribute sampler outside the SDK?

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#38]
Potentially: provide the sampler in a standalone artifact, if there's a use case for people using vanilla OTEL that want the deterministic sampler.

**Comment by JamieDanielson** [comment]
Removing stale, should only be on new issues as of Sept 1.

**Comment by MikeGoldsmith** [comment]
We’re going to close this for now. Feel free to re-open, if it’s still relevant.
