### ISSUE TITLE
List this project in the OTel Registry

### ISSUE THREAD

**Issue by bdarfler** [honeycombio/honeycomb-opentelemetry-java#47]
https://github.com/open-telemetry/opentelemetry.io#adding-a-project-to-the-opentelemetry-registry

**Comment by JamieDanielson** [comment]
Removing stale, should only be on new issues as of Sept 1.

**Comment by JamieDanielson** [comment]
Submitted PR: https://github.com/open-telemetry/opentelemetry.io/pull/762

Will close once merged.

**Comment by JamieDanielson** [comment]
Merged!
