### ISSUE TITLE
Automate Nexus publish

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#66]
Currently there's a manual step in our release process (need to close and release staged repositories in Sonatype UI). Automate that last bit as described [here](https://madhead.me/posts/no-bullshit-maven-publish/) using the [publish plugin](https://plugins.gradle.org/plugin/io.github.gradle-nexus.publish-plugin/1.1.0)

**Comment by JamieDanielson** [comment]
Removing stale, should only be on new issues as of Sept 1.
