### ISSUE TITLE
Document Debugging

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-java#91]
Folks are confused when it comes to using vanilla OTEL env vars/system properties with the beestro. Add something to the docs/readme about how those interact with the beestro (for example, you should be able to enable agent debug with `otel.javaagent.debug` but you might override honeycomb api key, if you set `otel.exporter.otlp.headers`)

slack thread: https://houndsh.slack.com/archives/C8RP24A6Q/p1627944971012200

**Comment by JamieDanielson** [comment]
Removing stale, should only be on new issues as of Sept 1.

**Comment by MikeGoldsmith** [comment]
Would be nice to have debug one for troubleshooting, maybe link to OTEL docs for all available ones.

**Comment by bdarfler** [comment]
Rebranding this as documentation for `otel.javaagent.debug` to debug the agent and  https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/logging/src/main/java/io/opentelemetry/exporter/logging/LoggingSpanExporter.java to debug manual instrumentation via logging output.
